sudo: required

services:
- docker

script:
- docker build -t theftcomm .

before_deploy:
- docker run --rm -it -v $(pwd):/out theftcomm cp /usr/local/bin/theftcomm /out

deploy:
  provider: releases
  api_key:
    secure: JYJtLp6Au1bqxyWC0fsjucJOcBvITqSVdhEuJnGKyI1WE13TwCxykA6W8OnZ6jPeUq901gS0FN0stFUfgfRgpgEiF/1uu/9U/0s49SDciN2TmsW/z8IihMLk9C6jui/jUffLc7iQsmj9+YdgnYqX4ouA9e6dk59+5cQbZ+Qxnd7nOHHizq0C+KRwAYLLqsEYGNuFmJn1KsptfNQBU5s9VbrsCHW1yXaJAZLXJXy1JpkdbO80fFyOuZd483RunpFdHSsapRM8YU1nfWpRL9KBm6XWuB3rcaLsUI0odq8GcyFNkFycO3r2ENGdBsnMH55x55B7eEsFAYxSAGNHQF+EIQT8Av9NdKumctvamEnVx8FoddnP+1kOJFrq7/d1v7I7d7pbMByanXPFBE4WjR9JACmOqw0J99gjZwD249dB+ZGQnYuCOMSoNvfEN6j/d/hVEzDl3WRXssEhEJP1VK9WobqGNUMxipofq/VZoWURD78gtQCTATnUMzKAqlxfLk5gBBtK30AkF4iFcbmNPzV3h09T/ZmWctn7ixAYsj60ScHgMR1DZtf/L3M0wO8JALi8LchT3/hZGhoZxMcW1ITVghVciHXqenlq+e+qYGvdbDcg4PzXxRZd2b0Wo3GcC+EnVLnY6fObx35CmLK5nu/jxB/KhVlAts3RDaDfMlXr9Do=
  file: theftcomm
  skip_cleanup: true
  on:
    repo: mitsfs/theftcomm
    tags: true
